(part "TPS5430DDA"
    (packageRef "SOIC127P600X170-9N")
    (interface
        (port "1" (symbPinId 1) (portName "BOOT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VSENSE") (portType INOUT))
        (port "5" (symbPinId 5) (portName "ENA") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VIN") (portType INOUT))
        (port "8" (symbPinId 8) (portName "PH") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS5430DDA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS5430DDA?qs=zwk82MlA57bk5fOPRvfoCA%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS5430DDA")
    (property "Description" "TPS5430DDA, Switching Regulator, Buck Controller, 3A, Adjustable, 1.22 to 31V, 500kHz, 8-Pin SOIC")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets-SFU2/DSASFU100034215.pdf")
    (property "symbolName1" "TPS5430DDA")
)
