(part "C4532X5R1C336M250KA"
    (packageRef "C4532_Commercial")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "810-C4532X5R1C336M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TDK/C4532X5R1C336M250KA?qs=NRhsANhppD8boSYbSECPsw%3D%3D")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "C4532X5R1C336M250KA")
    (property "Description" "MULTILAYER CERAMIC CHIP CAPACITORS, 4532, Commercial grade, general (Up to 75V)")
    (property "Datasheet_Link" "https://product.tdk.com/system/files/dam/doc/product/capacitor/ceramic/mlcc/catalog/mlcc_commercial_general_en.pdf")
    (property "symbolName1" "C4532X5R1C336M250KA")
)
