(part "1735265-8"
    (packageRef "17352658")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "MP1" (symbPinId 9) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 10) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-1735265-8")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-AMP/1735265-8?qs=vkMqrgFpRajjm%252BbPDw7SSA%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "1735265-8")
    (property "Description" "Body Features: Primary Product Color Natural | Configuration Features: Compatible With Wire & Cable Type FFC | Number of Positions 8 | Number of Rows 1 | PCB Mount Orientation Right Angle | Compatible With Wire & Cable Type FPC | Contact Features: Contact Mating Location Bottom | Contact Mating Area Plating Material Thickness 2 MICIN | Contact Shape & Form Standard Flat | Contact Mating Area Plating Material Gold | Contact Type Socket | Contact Base Material Phosphor Bronze | PCB Contact Termination Area Pl")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1-1773959-7-FPC-Connectors-CN&DocType=Data%20Sheet&DocLang=Chinese (Simplified)&PartCntxt=1735265-8&DocFormat=pdf")
    (property "symbolName1" "1735265-8")
)
