(part "MGAH06033R3M-10"
    (packageRef "INDPM7066X310N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Laird Performance Materials")
    (property "Manufacturer_Part_Number" "MGAH06033R3M-10")
    (property "Mouser_Part_Number" "739-MGAH06033R3M-10")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Laird-Performance-Materials/MGAH06033R3M-10?qs=By6Nw2ByBD2mXVegrURTAA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Power Inductors - SMD 3.3uH 0.03ohm 9.5A")
    (property "Datasheet_Link" "https://www.mouser.fr/datasheet/2/987/MGAH0603_2520Series-3043308.pdf")
    (property "symbolName1" "MGAH06033R3M-10")
)
