(part "ECS-250-8-36CKM-TR3"
    (packageRef "ECS250836CKMTR3")
    (interface
        (port "1" (symbPinId 1) (portName "IN/OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUT/IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Mouser_Part_Number" "520-250-8-36CKM-TR3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ECS/ECS-250-8-36CKM-TR3?qs=e8oIoAS2J1SEILtnBWQaUQ%3D%3D")
    (property "Manufacturer_Name" "ECS")
    (property "Manufacturer_Part_Number" "ECS-250-8-36CKM-TR3")
    (property "Description" "Crystals 25MHz,CL 8,TOL +/-10 ppm,STAB +/-10 ppm,-20 +70 C,ESR O60")
    (property "Datasheet_Link" "")
    (property "symbolName1" "ECS-250-8-36CKM-TR3")
)
