(part "F52R-1A7H1-11008"
    (packageRef "F52R1A7H111008")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "MP1" (symbPinId 9) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 10) (portName "MP2") (portType INOUT))
        (port "MP3" (symbPinId 11) (portName "MP3") (portType INOUT))
        (port "MP4" (symbPinId 12) (portName "MP4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "649-F52R-1A7H1-11008")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Amphenol-Aorora/F52R-1A7H1-11008?qs=xZ%2FP%252Ba9zWqZEjx1hhk5Q2Q%3D%3D")
    (property "Manufacturer_Name" "Amphenol Communications Solutions")
    (property "Manufacturer_Part_Number" "F52R-1A7H1-11008")
    (property "Description" "Flex Connector, 1.00mm Pitch, Height 2.00mm, Right angle, Slider type, ZIF, Bottom contact, 8 position , Without MYLAR")
    (property "Datasheet_Link" "https://cdn.amphenol-cs.com/media/wysiwyg/files/drawing/f52r.pdf")
    (property "symbolName1" "F52R-1A7H1-11008")
)
