(part "CM7V-T1A-32_768KHZ-7PF-20PPM-T"
    (packageRef "CM7V32768TBQA020")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Mouser_Part_Number" "428-201345-MG01")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Micro-Crystal/CM7V-T1A-32.768kHz-7pF-20PPM-TA-QC?qs=7bTaA%2FLYtSYA2NGDS9ZOKA%3D%3D")
    (property "Manufacturer_Name" "Micro Crystal AG")
    (property "Manufacturer_Part_Number" "CM7V-T1A-32.768KHZ-7PF-20PPM-TA-QC")
    (property "Description" "CRYSTAL 32.768KHZ SMD")
    (property "Datasheet_Link" "https://www.microcrystal.com/fileadmin/Media/Products/32kHz/Datasheet/CM7V-T1A.pdf")
    (property "symbolName1" "CM7V-T1A-32_768KHZ-7PF-20PPM-T")
)
