(part "TST-105-01-L-D"
    (packageRef "TST-105-XX-Y-D")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "200-TST10501LD")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Samtec/TST-105-01-L-D?qs=rU5fayqh%252BE3T4XEa6zyGyQ%3D%3D")
    (property "Manufacturer_Name" "SAMTEC")
    (property "Manufacturer_Part_Number" "TST-105-01-L-D")
    (property "Description" "10 Position, Shrouded PCB Headers, 0.100&quot; pitch")
    (property "Datasheet_Link" "http://suddendocs.samtec.com/prints/tst-1xx-xx-x-x-xx-xx-mkt.pdf")
    (property "symbolName1" "TST-105-01-L-D")
)
