(part "SP4065-08ATG"
    (packageRef "SOP50P488X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "I/O_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "I/O_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "I/O_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "I/O_4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND") (portType INOUT))
        (port "7" (symbPinId 7) (portName "I/O_5") (portType INOUT))
        (port "8" (symbPinId 8) (portName "I/O_6") (portType INOUT))
        (port "9" (symbPinId 9) (portName "I/O_7") (portType INOUT))
        (port "10" (symbPinId 10) (portName "I/O_8") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "576-SP4065-08ATG")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Littelfuse/SP4065-08ATG?qs=0Dbrz4iFQy%2FklE79eCp2zA%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "SP4065-08ATG")
    (property "Description" "LITTELFUSE - SP4065-08ATG - DIODE, ESD PROTECTION, 3.3V, MSOP")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/SP4065-08ATG.pdf")
    (property "symbolName1" "SP4065-08ATG")
)
